"""Create users and items tables3

Revision ID: 7a5c6e39869d
Revises: 53b35e5b03d2
Create Date: 2026-03-22 11:51:59.655675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5c6e39869d'
down_revision: Union[str, Sequence[str], None] = '53b35e5b03d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('Review', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'Review')
    # ### end Alembic commands ###
