"""fix_user_table1

Revision ID: bf62eae8753e
Revises: 
Create Date: 2026-04-07 08:25:37.299679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf62eae8753e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('title', sa.String(), nullable=True))
    op.add_column('items', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'])
    op.drop_column('items', 'name')
    op.drop_column('items', 'created_at')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'hashed_password')
    op.add_column('items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.alter_column('items', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('items', 'owner_id')
    op.drop_column('items', 'is_available')
    op.drop_column('items', 'stock')
    op.drop_column('items', 'title')
    # ### end Alembic commands ###
